### PR TITLE
Update data.js

### PR DESCRIPTION
**Pull request by Redforce04**
Update to apocalypse v0.7.0.0. Update patch notes are based off of [Insym's leaked release notes]( https://www.youtube.com/watch?v=r0KljGaNXpY), but can be changed tomorrow if the notes are updated or incorrect. 

Feel free to check through and make changes as necessary. 
@un0btanium @BotiKis

### CODE REVIEW

**Comment by BotiKis** [comment]
Damn you where faster :D! haha good job :).
Everything confirmed but I would adjust the text of the myling too:

`"During a hunt footstep sounds can only be heard when 10m or closer (similar to electronic interference)"`
to
`"During a hunt all hunting sounds can only be heard when 10m or closer"`
This was written before it was known that this was a bug.

I don't want to open a pr for this so here you go.

**Comment by Redforce04** [comment]
Updated the PR with @BotiKis suggestion. 

@un0btanium Should be ready for pull now.

**Comment by Redforce04** [comment]
Just checked the patch notes and it looks like they haven't majorly changed. Should be accurate according to what we have already changed.

**Comment by un0btanium** [comment]
Thank you for your continuous support. Much appreciated. Glad you still enjoy the game and find this website useful 👍

**Pull request merged**
