### PR TITLE
Updated ghost data after 0.5.2 update

### PR DESCRIPTION
**Pull request by BotiKis**
## Update 0.5.2
Today a smaller patch was released adjusting some ghost behaviour and many bugfixes.
Fortunately they started to clearly mention what has changed so I could simply just take the information over.

[Read Official patchnotes](https://store.steampowered.com/news/app/739630?emclan=103582791466524086&emgid=5708878651027615740)

### CODE REVIEW

**Comment by BotiKis** [comment]
@un0btanium 🙏

**Comment by un0btanium** [comment]
@BotiKis If you fix that one line at 190 I will merge and deploy it asap :)

**Comment by BotiKis** [comment]
@un0btanium Sure I'll do! Do you mean the 0° typo or to rephrase that line since it is not really helpful?

`"1.4 m/s= 15°C+ | 1.5 m/s= 12°C | 1.65 m/s= 9°C | 1.8 m/s= 6°C | 2.2 m/s= 3°C | 2.5 m/s= 0°C",`

Maybe something like:
`"Slowest at 15°C+ and gradually gets faster at 12°C, 9°C, 6°C, 3°C, until 0°C",`

**Comment by un0btanium** [comment]
@BotiKis The format is fine and informative. I like it.
My issue is the last entry. Read the last three entires: **1.8 m/s= 6°C** | 2.2 m/s= 3°C | **1.8 m/s= 6°C**
The last one is a repeat. Going by your new example, the 2.5 m/s=0°C entry seems to be the correct one.

**Comment by BotiKis** [comment]
@un0btanium great - fixed :)!

**Pull request merged**
